name: Main Workflow

on:
  push:
  workflow_dispatch:

jobs:
  RunUnitTest:
    uses: 'https://github.com/TuyetPhuong/Demo/tree/main/.github/workflows/unit-test.yml@main'

  RunCheckStyle:
    uses: 'https://github.com/TuyetPhuong/Demo/tree/main/.github/workflows/check-style.yml@main'
